clf, close all;
% Create axes for placing a background 
f = figure;
ha = axes('units','normalized', 'position',[0 0 1 1]);
uistack(ha,'top');
% Read the background and scale it 
I=imread('../ImageLIB/back.jpg');
hi = imagesc(I);

% Display the axes
set(ha,'handlevisibility','off', 'visible','off');

% Make the title
uicontrol( 'Style','Text',...
                'BackgroundColor',[.0 .0 .0],...
                'ForegroundColor',[.3 .55 .71],...
                'units', 'normalized', ...                
                'position', [0 0.9 1 0.1],...
                'string', 'Digital Image Enhancement', ...
                'HorizontalAlignment', 'center', ...
                'fontsize', 25, ...
                'Fontweight', 'bold', ...
                'HandleVisibility', 'off');
uicontrol( 'Style','Text',...
                'BackgroundColor',[.0 .0 .0],...
                'ForegroundColor',[.3 .55 .71],...
                'units', 'normalized', ...                
                'position', [0 0.80 1 0.1],...
                'string', '"Spatial Domain', ...
                'HorizontalAlignment', 'center', ...
                'fontsize', 25, ...
                'Fontweight', 'bold', ...
                'HandleVisibility', 'off');

 % Defining parameters
 left = 0.1;
 w = 0.3;
 h = 0.07;
            
% Place the buttons on the left     
u1 = uicontrol('Style','push','units','normalized', 'pos',...
                [left 0.7 w h],'string','Original image',...
                'ForegroundColor',[1 .0 .0],...
                'Fontweight', 'bold', ...
                'Callback', 'DIF_Orig');  
            
u2 = uicontrol('Style','push','units','normalized', 'pos',...
                [left 0.55 w h],'string','FFT',...
                'Callback', 'DIEF_FFT');  
            
u3 = uicontrol('Style','push','units','normalized', 'pos',...
                [left 0.5 w h],'string','FFT LP',...
                'Callback', 'DIEF_FFT_LP');
            
u4 = uicontrol('Style','push','units','normalized', 'pos',...
                [left 0.4 w h],'string','FFT HP',...
                'Callback', 'DIEF_FFT_HP'); 

%Align them all            
align([u1 u2 u3 u4],'Left','Fixed', 5);

            