clf, close all;
% Create axes for placing a background 
f = figure;
ha = axes('units','normalized', 'position',[0 0 1 1]);
uistack(ha,'top');
% Read the background and scale it 
I=imread('../ImageLIB/back.jpg');
hi = imagesc(I);

% Display the axes
set(ha,'handlevisibility','off', 'visible','off');

% Make the title
uicontrol( 'Style','Text',...
                'BackgroundColor',[.0 .0 .0],...
                'ForegroundColor',[.3 .55 .71],...
                'units', 'normalized', ...                
                'position', [0 0.9 1 0.1],...
                'string', 'Digital Image Enhancement', ...
                'HorizontalAlignment', 'center', ...
                'fontsize', 25, ...
                'Fontweight', 'bold', ...
                'HandleVisibility', 'off');
uicontrol( 'Style','Text',...
                'BackgroundColor',[.0 .0 .0],...
                'ForegroundColor',[.3 .55 .71],...
                'units', 'normalized', ...                
                'position', [0 0.80 1 0.1],...
                'string', '"Spatial Domain', ...
                'HorizontalAlignment', 'center', ...
                'fontsize', 25, ...
                'Fontweight', 'bold', ...
                'HandleVisibility', 'off');

 % Defining parameters
 left = 0.1;
 w = 0.3;
 h = 0.07;
            
% Place the buttons on the left     
u1 = uicontrol('Style','push','units','normalized', 'pos',...
                [left 0.7 w h],'string','Original image',...
                'ForegroundColor',[1 .0 .0],...
                'Fontweight', 'bold', ...
                'Callback', 'DIF_Orig');  
            
u2 = uicontrol('Style','push','units','normalized', 'pos',...
                [left 0.55 w h],'string','Inverse image',...
                'Callback', 'DIE_Inverse');  
            
u3 = uicontrol('Style','push','units','normalized', 'pos',...
                [left 0.5 w h],'string','Log Transformation',...
                'Callback', 'DIE_LogTransform');
            
u4 = uicontrol('Style','push','units','normalized', 'pos',...
                [left 0.4 w h],'string','Power Law Transformation',...
                'Callback', 'DIE_PowerLawTransform'); 
            
u5 = uicontrol('Style','push','units','normalized', 'pos',...
                [left 0.3 w h],'string','Contrast Streching (PWL)',...
                'Callback', 'DIE_ContrastStreching');  
            
u6 = uicontrol('Style','push','units','normalized', 'pos',...
                [left 0.2 w h],'string','Gray-level slicing',...
                'Callback', 'DIE_GrayLevelSlicing');
            
u7 = uicontrol('Style','push','units','normalized', 'pos',...
                [left 0.18 w h],'string','Bit-plane Slicing (8-bit)',...
                'Callback', 'DIE_BitplaneSlicing');  
%Align them all            
align([u1 u2 u3 u4 u5 u6 u7],'Left','Fixed', 5);


%Align right
left = 0.63;

% Place the buttons on the right       
u11 = uicontrol('Style','push','units','normalized', 'pos',...
                [left 0.7 w h],'string','Histogram shrinking',...
                'ForegroundColor',[.1 .5 .0],...
                'Callback', 'DIE_HistogramShrinking');  
            
u12 = uicontrol('Style','push','units','normalized', 'pos',...
                [left 0.55 w h],'string','Histogram Stretching',...
                'ForegroundColor',[.1 .5 .0],...
                'Callback', 'DIE_HistogramStreching');  
            
u13 = uicontrol('Style','push','units','normalized', 'pos',...
                [left 0.5 w h],'string','Histogram Equalization',...
                'ForegroundColor',[.1 .5 .0],...
                'Callback', 'DIE_HistogramEqualisation');
            
%u14 = uicontrol('Style','push','units','normalized', 'pos',...
%                [left 0.4 w h],'string','Histogram Sliding',...
%                'ForegroundColor',[.1 .5 .0],...
%                'Callback', 'DIE_HistogramSliding'); 

u15 = uicontrol('Style','push','units','normalized', 'pos',...
                [left 0.3 w h],'string','Image Addition',...
                'ForegroundColor',[.1 .1 .5],...
                'Callback', 'DIE_ImageAddition');  
            
u16 = uicontrol('Style','push','units','normalized', 'pos',...
                [left 0.2 w h],'string','Image Subtraction',...
                'ForegroundColor',[.1 .1 .5],...
                'Callback', 'DIE_ImageSubtraction');
            
u17 = uicontrol('Style','push','units','normalized', 'pos',...
                [left 0.19 w h],'string','Image Smoothing(LP)filter',...
                'ForegroundColor',[.5 .0 .5],...
                'Callback', 'DIE_ImageSmoothingLP');  
            
u18 = uicontrol('Style','push','units','normalized', 'pos',...
                [left 0.18 w h],'string','Image Sharpening(HP)filter',...
                'ForegroundColor',[.5 .0 .5],...
                'Callback', 'DIE_ImageSharpening');  
            
            
align([u11 u12 u13  u15 u16 u17 u18],'Right','Fixed', 5);
            